[package]
name = "scada-foundry-service"
version = "0.1.0"
edition = "2024"

[dependencies]
rusty-acse = { git = "https://github.com/gazzasaur/rusty-iccp", version = "*" }
rusty-copp = { git = "https://github.com/gazzasaur/rusty-iccp", version = "*" }
rusty-cosp = { git = "https://github.com/gazzasaur/rusty-iccp", version = "*" }
rusty-cotp = { git = "https://github.com/gazzasaur/rusty-iccp", version = "*" }
rusty-iccp = { git = "https://github.com/gazzasaur/rusty-iccp", version = "*" }
rusty-mms = { git = "https://github.com/gazzasaur/rusty-iccp", version = "*" }
rusty-mms-service = { git = "https://github.com/gazzasaur/rusty-iccp", version = "*" }
rusty-tpkt = { git = "https://github.com/gazzasaur/rusty-iccp", version = "*" }

serde = "1.0.228"
anyhow = "1.0.102"
tracing = "0.1.44"
async-trait = "0.1"
thiserror = "2.0.18"
der-parser = "10.0.0"
tracing-subscriber = "0.3.23"
num-bigint = { version = "0.4.6" }
axum = { version = "0.8.9", features = ["ws"] }
uuid = { version ="1.23.1", features = ["v4"] }
hex = { version = "0.4.3", features = ["serde"] }
oid = { version = "0.3.0", features = ["serde"] }
clap = { version = "4.6.1", features = ["derive"] }
tokio = { version = "1.52.3", features = ["full"] }
bigdecimal = { version = "0.4", features = [ "serde-json" ] }
axum-extra = { version = "0.12.6", features = ["typed-header"] }
serde_json = { version = "1.0.149", features = ["arbitrary_precision"] }
futures = "0.3.32"
rand = "0.10.1"
